# Generated by Django 4.1.5 on 2023-02-02 16:35

from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publisher", "0001_initial"),
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "isbn",
                    isbn_field.fields.ISBNField(
                        clean_isbn=False,
                        max_length=28,
                        validators=[isbn_field.validators.ISBNValidator],
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=1000, verbose_name="Description"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Books",
                        to="author.author",
                        verbose_name="Author",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Books",
                        to="publisher.publisher",
                        verbose_name="Publisher",
                    ),
                ),
            ],
        ),
    ]
