# Generated by Django 4.1.5 on 2023-02-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_book_date_published_book_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
