# Generated by Django 4.1.5 on 2023-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantity"),
        ),
    ]
