# Generated by Django 4.1.5 on 2023-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
        ("book", "0004_book_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ManyToManyField(
                related_name="Books", to="author.author", verbose_name="Author"
            ),
        ),
    ]
