# Generated by Django 4.1.5 on 2023-02-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_remove_book_author_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="author",
            new_name="authors",
        ),
    ]
