# Generated by Django 4.1.5 on 2023-02-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
    ]
