# Generated by Django 4.1.5 on 2023-02-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publisher", "0002_alter_publisher_options"),
        ("book", "0008_alter_book_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Books",
                to="publisher.publisher",
                verbose_name="Publisher",
            ),
        ),
    ]
